### ISSUE TITLE
Unable to download meta file from NVD due to connection timeout in OWASP Dependency-Check

### ISSUE THREAD

**Issue by ParkSangsin** [fosslight/fosslight_binary_scanner#124]
**Describe the bug**
I encountered a persistent issue where OWASP Dependency-Check is unable to download the meta file from NVD. The error message indicates a timeout while trying to connect to the NVD server.

[fosslight_report_all_240922_0643.xlsx](https://github.com/user-attachments/files/17088792/fosslight_report_all_240922_0643.xlsx)

**To Reproduce**
1. Run OWASP Dependency-Check to scan dependencies.
2. The tool attempts to download CVE meta files from NVD.
3. The process fails with a SocketTimeoutException

**Expected behavior**
The meta file from NVD should download successfully and allow the dependency analysis to continue.

**Screenshots**
![image](https://github.com/user-attachments/assets/45a8e7a8-1676-4f1d-bacd-bd7a9bea9302)

**System Environment (please complete the following information):**
 - Etc

**Additional context**

**Comment by soonhong99** [comment]
제가 살펴보니 제대로 동작한 fosslight_scanner version은 v2.0.0 이었고, 현재 v2.0.1 버전, 즉 최신버전은 prechecker를 넣는 과정에서 time out이 설정되었는지, db가 온전히 설치되기 전에 실행되는 것 같습니다.

**Comment by soonhong99** [comment]
NVD CVE를 업데이트 하고 난 후 완료가 되었으면 그때 binary 분석을 시도하는데 업데이트를 하지 못하므로 binary 분석을 하지 못하는 것으로 보입니다.

**Comment by soonhong99** [comment]
fosslight binary 분석이 된 log 파일 입니다.
[fosslight_log_20240923_0244.txt](https://github.com/user-attachments/files/17090659/fosslight_log_20240923_0244.txt)

**Comment by soonhong99** [comment]
fosslight binary 분석이 되지 않은 log 파일입니다.
[fosslight_log_20240922_1541.txt](https://github.com/user-attachments/files/17090663/fosslight_log_20240922_1541.txt)

**Comment by soonhong99** [comment]
fosslight_scanner 실행을 어디서 하냐 차이인 것 같습니다. 
어제 진행한 오프라인 모임에서 fosslight_scanner 실행했을 때는 NVM update timeout이 발생하였지만 
현재 집에서 실행한 결과 해당 오류가 발생하지 않았습니다.

**Comment by ParkSangsin** [comment]
저도 집에서 실행해 보니 잘 동작하네요!
[fosslight_log_20240923_1033.txt](https://github.com/user-attachments/files/17092188/fosslight_log_20240923_1033.txt)
[fosslight_report_all_240923_0137.xlsx](https://github.com/user-attachments/files/17092190/fosslight_report_all_240923_0137.xlsx)
