### ISSUE TITLE
The number of columns in the csv bin does not match.

### ISSUE THREAD

**Issue by riyenas0925** [fosslight/fosslight_binary_scanner#18]
**Describe the bug**
file with bugs : [FOSSLight-Report_20211005_171931_BIN.csv](https://github.com/fosslight/fosslight_binary_scanner/files/7319934/FOSSLight-Report_20211005_171931_BIN.csv)

The number of columns in the header is exactly the same, but there is one more column in the row below.
![image](https://user-images.githubusercontent.com/32615702/136742852-b0d57a46-f2c0-4e8e-9c04-02f522d31e09.png)

Therefore, when importing csv, the wrong value inputs as below.
![image](https://user-images.githubusercontent.com/32615702/136743475-6bec5dea-9230-4aa1-bb99-64c41a5a0f24.png)

**Expected behavior**
the number of columns in row must match the header.

**Comment by soimkim** [comment]
@riyenas0925 , Thanks for reporting the bug.
