### ISSUE TITLE
Can't connect to Binary DB. :could not translate host name "bat.lge.com" to address: Unknown host

### ISSUE THREAD

**Issue by kiranravindran90** [fosslight/fosslight_binary_scanner#21]
Hi, I installed Fosslight successfully & setup the virtual environment also. But when ran the tool, I am getting the below shown log & outputs just have the file names but no other info.
Log :
------------------------------------------------------------------------------------------------------------------------------------
[  DEBUG] (Minor) Can't connect to Binary DB. :could not translate host name "bat.lge.com" to address: Unknown host

[  DEBUG] ITEM COUNT:11
[   INFO] Writing Output file(FOSSLight-Report_20211202_132636.csv):True 
[   INFO] Binaries / Scanned files: 11 / 22
Execution result: Success
FOSSLight binary.txt: C:\<output_path>\binary_20211202_132636.txt
Identified in Binary DB / Binaries: 0 / 11
OS: Windows 10
Output file: C:\<output_path>\FOSSLight-Report_20211202_132636.csv
Path to analyze: C:\Kiran_Ravindran\My_Tasks\01_Ongoing\06_FOSS\99_Resources\Flashwares\HU7
Python version: 3
Running time: ' ~ 20211202_133135'
Tool Info: fosslight_binary v4.0.2
------------------------------------------------------------------------------------------------------------------------------------

Not sure why it isn't connecting to Binary DB. Let know if i have missed something.

**Comment by soimkim** [comment]
If you want to use Binary DB, you need to set up Binary DB first. : https://fosslight.org/fosslight-guide-en/scanner/etc/binary_db.html

And when running fosslight_binary, you have to pass the db information with the -d option.

Please refer to this link for more details.
- https://fosslight.org/fosslight-guide-en/scanner/4_binary.html

**Comment by soimkim** [comment]
Let me know if you have any more questions.

**Comment by kiranravindran90** [comment]
Thanks a lot for the info.
